# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('humi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('CO2', models.CharField(max_length=5)),
                ('light', models.BooleanField(default=True)),
                ('watp', models.BooleanField(default=True)),
            ],
        ),
    ]
