from Recon import Recon
import time
control = Recon()

control.light_on()
time.sleep(1)
control.light_off()
time.sleep(1)
control.light_on()
time.sleep(1)
control.light_off()
time.sleep(1)
control.light_on()
time.sleep(1)
control.light_off()
time.sleep(1)
control.light_on()
time.sleep(1)
control.light_off()
time.sleep(1)
control.light_on()
time.sleep(1)
control.light_off()
time.sleep(1)
