from Recon import Recon
import time
control = Recon()

control.light_on()
time.sleep(1)
control.light_off()
time.sleep(1)
control.humi_on()
time.sleep(1)
control.humi_off()
time.sleep(1)
control.com_on()
time.sleep(1)
control.com_off()
time.sleep(1)
control.pump_on()
time.sleep(1)
control.pump_off()
time.sleep(1)
control.light_on()
time.sleep(1)
control.light_off()
time.sleep(1)
control.pump_on()
time.sleep(1)
control.pump_off()
time.sleep(1)
control.pump_on()
time.sleep(1)
control.pump_off()
time.sleep(1)
